### ISSUE TITLE
XSLT Assignment Rewriting

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/newtFire-webDev#6]

**Comment by ebeshero** [comment]
@andrewntz23 Andrew, may I ask you to help us get started with the first major task in our reinvention of Obdurodon's XSLT series? We need to locate base texts to use for the sequence, to replace:
- bad Hamlet
- Skyrim
- Shakespeare's sonnets

Would you be willing to investigate some alternative texts we could use, and perhaps link to or otherwise push them here for us to consider? The only reason I'm not doing this myself today is because I'm visiting with Helena Bermudez-Sabel and we're working on an XSLT project together--she's only here for a short time and today's our only day to meet face-to-face before she returns to Spain. If you can help with identifying at least one or two good texts today, that would help us to get started with revising assignments.

In thinking of good replacements, here's something to consider: Perhaps our replacement XML should be a little different in hierarchical structure somehow from the one that Obdurodon is using. So, perhaps a sequence of sonnets by some-other-poet-not-Shakespeare isn't quite what we're after. We need something that won't output the same number of lines(?) or might have some other interesting quirks. Perhaps we might find a collection of sonnets that is laid out differently, dividing the octave (first eight lines) from the sestet (last six lines) with a white space (requiring a slightly different hierarchy but otherwise similar).

It doesn't matter where we begin, I think: We need base texts in well-formed XML to start with, with enough complexity to help us adapt the same or similar features of each assignment. You could begin with whatever assignment (or assignment-cluster) you like, but let's just see if we can collect some texts to begin with. Thanks hugely for your help!

I'm estimating, by the way, that the remaining rewrites might not take us terribly long--but that we will need to work together through the weekend, if that's okay. David has just written to you to extend your time assisting us a little longer.

Once we've identified some base texts, we'll need to a) review what Alex has come with for the last XPath assignment, and then b) we can dive in together to rewrite (and proof) new XSLT assignments. @alexkrongel @RJP43 

Many thanks for your help! 

Elisa

**Comment by ebeshero** [comment]
I have some ideas for base files to use for the XSLT  assignments pulled from the Mitord, Nelson, and some of my Southey projects, so I'll tinker a bit and post more in a few hours. @RJP43 Becca, are you okay with my pulling from the Nelson project files? @andrewntz23  @alexkrongel

**Comment by ebeshero** [comment]
Okay: I've got a beginning; In place of Shakespeare's sonnets (at least), I think we can use the Digital Mitford site index, for the opening XSLT assignments: [http://digitalmitford.org/si.xml](http://digitalmitford.org/si.xml)

**Comment by RJP43** [comment]
In place of the Skyrim file, I have added an [edited version of the first article from the City Slave Girls series (Nell Nelson Project)](https://github.com/ebeshero/newtFire-webDev/blob/master/dh-course/XSLT-Ex2Ex3_BaseText_NelsonArticle_1888-07-30.xml). The file is heavily marked up and there are now 3 elements linked with ref attributes ... company, workingConditions, location each linked with ref= "#companyName" .
For example:
 `<company name="identified" ref="#WLMC">“Western Lace Manufacturing Co.”</company>`
`<location type="address" ref="#WLMC">218 State street</location>`
`<workingConditions category="wageDesc" ref="#WLMC">the firm agreed to refund $1 of the $3 deposited when she had finished $15 worth of
        work</workingConditions>`

We can use these linked elements to form a table listings company names, exact addresses, and different types of working conditions (wageDesc=wage description positive/negative = descriptions of environement and/or treatment of employees) like in [Obdurodon XSLT Assignment 2](http://obdurodon.org/dh/xslt-assignment-02.xhtml)

And we can use the variety of different tags like  livingConditions vs workingConditions and/or Dialogue with each of the different voice elements to transform with `<span> <em> and <strong>` like in [Obdurodon XSLT Assignment 3](http://obdurodon.org/dh/xslt-assignment-03.xhtml)

@ebeshero We can simplify this file if need be, but I figured the more marked up the better because more to pull from... let me know.

**Comment by ebeshero** [comment]
@RJP43 Excellent--thank you, Becca! Your Nell Nelson file makes a great replacement to the Skyrim assignment.

@andrewntz23 @alexkrongel We now have identified base texts to use for all the assignments:

Replacements for Obdurodon's assignments:
- XSLT 1: Either the Digital Mitford site index or our upconverted XML of Pygmalion 
- XSLT 2 and 3: Becca's article from City Slave Girls
- XSLT 4 and 5: Digital Mitford's site index

I'm going to pound my revisions of these assignments in the morning, and I'll just ask for some help with proofreading and testing them!

Thanks everyone!

**Comment by ebeshero** [comment]
[XSLT Exercise 1](http://newtfire.org/dh/XSLTExercise1.html) is posted!

**Comment by ebeshero** [comment]
[XSLT Exercise 2](http://newtfire.org/dh/XSLTExercise2.html) is posted! Please have a look and let me know if you spot problems with either of these.

**Comment by RJP43** [comment]
[XSLT Exercise 3](https://github.com/ebeshero/newtFire-webDev/blob/8c59dcf66afa2064750bc1389c42008d6b0c9154/dh-course/XSLTExercise3.html) is ready to be proofread, tested, and then posted. @ebeshero
