### ISSUE TITLE
Oakland vs. Greensburg Grading System

### ISSUE THREAD

**Issue by zme1** [ebeshero/newtFire-webDev#96]
Considering the wealth of feedback that accompanied returned homework assignments to me this past spring throughout the semester, I think it would be more productive to expend more energy on written feedback and personalized response, rather than trying to determine where in the given spectrum a specific homework assignment would fall. In the same way, given that we will also be giving feedback on all assignments, the spectrum-based grading system might introduce some redundancy. Also (and this depends entirely on your personal grading philosophies, Greg, for I am basing my assessment solely on my experiences with Dr. Birnbaum), assignments that reflected authentic and thoughtful attempts at completing the homework (even if they were not fully completed) and/or explanations of obstacles that impeded an assignment's completion, along with attempted solutions to those impediments, were viewed and graded as sufficiently completed homework assignments. In this way, the focus was much more oriented toward the student's incremental growth as a digital scholar through his or her time with the homework. If the grading system itself were to become more nuanced and complex, I think some of the attention to that important facet of the homework may be diverted from focusing on growth and toward something more arbitrarily concerned with avoiding a lower grade on an assignment. My preferences are not very strong on this topic (and I imagine my opinion is much more biased than that of you, since both you and Elisa have unique experience with both systems), but I am in favor of guarding Dr. Birnbaum's homework system nonetheless.

**Comment by ebeshero** [comment]
@zme1 It may help to review some anonymized graded feedback from our "sibling variant" course to understand how we have applied scores. Applying numerical scores is an effort to increase clarity for students anxious about how they are doing--and the numbers are not applied in the way you may be used to seeing in other courses that apply "spectrum" grading. Where a student clearly demonstrates strong effort but confusion on a challenging assignment, the student still earns a (reassuring) high mark: perhaps an 8.5, 8.8, or 9 out of 10.  But where a student is clearly skipping tasks and doing the minimum to show they "get" the idea, it seems problematic to us to give them the same mark (the check) as the student who works diligently, researches, and documents what they tried. We also provide detailed commentary inspired by David's responses, because this is definitely the most important aspect of evaluating homeworks and teaching in the process. Additional to that commentary, the simple numbers have proven beneficial in nudging some of our students to work a little harder, and in reassuring our more anxious students that getting something wrong isn't a problem if they really applied themselves. 

In the end, we apply a generous point bonus in the Grade Center to all who, regardless of score, meet the 90% rule. That means that even students who earn low-ish marks for sketchy, undocumented work, but who *keep up* every day, are rewarded for persistence with at lowest a B+ homework score. Usually those students learn to write better code and documentation, and they have the satisfaction of seeing their scores improve over the course of the term. In my experience with Greensburg students, and really in my own experience of David's system, the ambiguous check marks generate anxiety: one does not know whether a check means "merely okay", or "pretty good", or "we would have given you this for uploading something you wrote in 30 minutes to Courseweb". One also doesn't know if one is improving much over time when a series of homeworks are "checked off" in the Grade Center. Looking at it from the low end of the spectrum, the Greensburg grading system is an effort to fend off assumptions that turning in just anything minimal is "good enough" to be content with one's progress. It seems to work to motivate our students, who are typically unused to nightly homework, or where they've had to do nightly homework in other courses, have found they don't need to work hard on it to "get by". Consider the score, then, as less a value assigned for absolute  correctness, and more a rhetorical, persuasive device whose aim is twofold:
1) motivating students to take the homework seriously when it's clear that little effort was applied, and 
2) reassuring students who are often skittish when they can't get their code to work. 
When students see they are clearly rewarded for trying hard, even when they don't get the desired results, they learn to trust us and understand that they really are doing well. (Just as some students are often trying to find the lowest amount of work that will satisfy, others are accustomed to being penalized for getting the wrong answer, which is definitely *not* our approach in either course!) 

I think in the end, the goal is the same, but we want to send clearer signals. We decided after discussion with the newtFire instructors that our students are less anxious when their work is returned with a numerical score in addition to our extensive commentary. In a way, the numbers do the same thing as the check, check-plus, check-minus system, but we find those evaluations not as clear as they could be, especially considering they are converted into numbers by the end of the course in calculating final grades. 

If you'd like to see some samples of our grading, I'm happy to send privately...I'll try making a sample folder to share with both sets of instructors.

**Comment by ebeshero** [comment]
@zme1 I should add that the numerical score is determined by the profs, not the student-instructors, who simply may suggest a score. The emphasis in grading is really, as ever, on generous, personalized commentary.

**Comment by zme1** [comment]
Dear Elisa,


Thank you for the clarification behind the more abstract purpose fulfilled by the numerical grading system. After reading through your defense (and in light of the fact that this system does not fall on the shoulders of the TA's), I am more than content with the implementation of whatever system you feel is most comfortable to both Gregory's and your teaching methods. I am excited to get started in this next month with you guys! Let me know if you need anything from me at all in the next month before classes start up.


Best,

Zachary


(P.S. Sorry for the delayed response to your message. I do not have constant access to my email, but will be much more deliberate with checking for updates throughout the remainder of the break.)

________________________________

**Comment by gabikeane** [comment]
Sorry again to be late to this party.  I agree with Elisa that the numerical system may help reduce student anxiety, but I'd like to add that I think part of the goal of this course is to give a graduate level research course experience.  To me, both as a student and a person grading, the question of "how am i doing?" was always determined by the feedback I got.  I'm one of the few TAs who received multiple check minuses-- but I always knew exactly why I was getting them (and they all had to do with my own time management issues).  Students who take the course tend to have that sort of self-reflecting and motivating attitude, so grades can be general or vague so long as feedback is clear.
That being said, I'm in favor of the numbered system for this semester.  It's proven to work time and again in Greensburg and I want to see if there's a difference.

**Comment by ghbondar** [comment]
@zme1 @gabikeane @amk231 Thanks for the great feedback and ideas... I am back in North America, at least (albeit in Ottawa, Ontario), and Elisa & I will be working on accelerating our preparations for the semester. Ultimately, the numerical grades provide an additional degree of granularity/detail to the process of evaluating assignments and providing feedback. As @ebeshero explained, you guys will not be expected to calculate the numerical grade on each assignment. While you are welcome to estimate a grade on those assignments that you are correcting, it will be only one of several things that I will consider in determining the student's grade on each assignment.
